### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mhdGit402** [mhdGit402/Lifestyle-Tracker#1]
Database:
User: name, password, email => There sould be some sort of profile so that users can see their streaks(with some fancy icon which indicate their streaks).
Lifestyle: Title, Start date, End date, User_id
Item: Title, Lifestyle_id
Tracker: Date, Items(as object with achived or failed data like=> {item1: true, item2: false , ...}),  Lifestyle_id => This table should filled  when user insert new data each day. Also there should be ability to insert data offline and when user get back online, if they insert any tracker, their data should be sync.
Streak: Streak_time(3 Days, 1 week, 2 week &  etc.), User_id, Lifestyle_id => This table should filled automatically by some sort of event and listener or something  simillar.

Notes:
- [x] 1- User can delete their lifestyle anytime they want but when they update it, their tracker & streak should be reset. (streak: todo)

- [ ] 2- If certain streak reached, show some toast real-time or after user logged in.

- [x] 3- Add view button to lifestyle

- [x] 4- submitted_date should check in "tracker" in order to avoid inserting duplicate date. (consider deleting time from submitted_date to avoid further bug)
- [x] 5- Relation between user and lifestyle and related policies.
